# Generated by Django 5.1.15 on 2026-05-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('story', 'Our Story'), ('sustainability', 'Sustainability')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('title_uz', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('subtitle_ru', models.CharField(blank=True, max_length=300)),
                ('subtitle_uz', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField()),
                ('body_ru', models.TextField(blank=True)),
                ('body_uz', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, upload_to='pages/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['page_key'],
            },
        ),
    ]
