# Generated by Django 5.1.15 on 2026-05-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_key', models.CharField(choices=[('home_hero', 'Homepage Hero'), ('home_story', 'Homepage Story Teaser'), ('home_featured', 'Homepage Featured Products')], max_length=50, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('title_uz', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('body_ru', models.TextField(blank=True)),
                ('body_uz', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='blocks/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('headline_ru', models.CharField(blank=True, max_length=200)),
                ('headline_uz', models.CharField(blank=True, max_length=200)),
                ('subheadline', models.CharField(blank=True, max_length=300)),
                ('subheadline_ru', models.CharField(blank=True, max_length=300)),
                ('subheadline_uz', models.CharField(blank=True, max_length=300)),
                ('cta_text', models.CharField(default='Learn More', max_length=50)),
                ('cta_text_ru', models.CharField(blank=True, max_length=50)),
                ('cta_text_uz', models.CharField(blank=True, max_length=50)),
                ('cta_url', models.CharField(default='/products/', max_length=200)),
                ('image', models.ImageField(upload_to='hero/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
